"""auto-vote

Revision ID: 112d38b121df
Revises: 7d61582845dd
Create Date: 2023-01-05 21:56:02.434473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112d38b121df'
down_revision = '7d61582845dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('users', 'Password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.drop_table('votes')
    # ### end Alembic commands ###
